<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
		<RootNamespace>ControllerPlayground</RootNamespace>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<Platforms>x86;x64;ARM64</Platforms>
		<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
		<PublishProfile>win-$(Platform).pubxml</PublishProfile>
		<UseWinUI>true</UseWinUI>
		<EnableMsixTooling>true</EnableMsixTooling>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="Controls\ActivityFeedCard.xaml" />
	  <None Remove="Controls\ControllerGlyph.xaml" />
	  <None Remove="Controls\ControllerPrompt.xaml" />
	  <None Remove="Controls\ControllerPromptBar.xaml" />
	  <None Remove="Controls\FriendActivityCard.xaml" />
	  <None Remove="Controls\PlayedFriendAvatar.xaml" />
	  <None Remove="Controls\SteamChatMessageBubble.xaml" />
	  <None Remove="Controls\SteamFriendCard.xaml" />
	  <None Remove="Overlays\FriendChatPane.xaml" />
	  <None Remove="Overlays\FriendsOverlay.xaml" />
	  <None Remove="Overlays\GameContextMenu.xaml" />
	  <None Remove="Overlays\GuideMenu.xaml" />
	  <None Remove="Overlays\SteamQrLoginOverlay.xaml" />
	  <None Remove="Views\FriendsView.xaml" />
	  <None Remove="Views\GameActivityView.xaml" />
	  <None Remove="Views\HomeView.xaml" />
	  <None Remove="Views\SettingsView.xaml" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.GameInput" Version="3.5.268" />
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="2.3.1" />
		<PackageReference Include="QRCoder" Version="1.8.0" />
		<PackageReference Include="SteamKit2" Version="3.4.0" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Assets\SplashScreen.scale-200.png" />
		<Content Include="Assets\LockScreenLogo.scale-200.png" />
		<Content Include="Assets\Square150x150Logo.scale-200.png" />
		<Content Include="Assets\Square44x44Logo.scale-200.png" />
		<Content Include="Assets\Square44x44Logo.targetsize-24_altform-unplated.png" />
		<Content Include="Assets\StoreLogo.png" />
		<Content Include="Assets\Wide310x150Logo.scale-200.png" />
	</ItemGroup>

	<ItemGroup>
		<Manifest Include="$(ApplicationManifest)" />
	</ItemGroup>

	<!--
    Defining the "Msix" ProjectCapability here allows the Single-project MSIX Packaging
    Tools extension to be activated for this project even if the Windows App SDK Nuget
    package has not yet been restored.
  -->
	<ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
		<ProjectCapability Include="Msix" />
	</ItemGroup>
	<ItemGroup>
		<Page Update="Controls\GameTile.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>

	<!--
    Defining the "HasPackageAndPublishMenuAddedByProject" property here allows the Solution
    Explorer "Package and Publish" context menu entry to be enabled for this project even if
    the Windows App SDK Nuget package has not yet been restored.
  -->
	<PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
		<HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
	</PropertyGroup>

	<!-- Publish Properties -->
	<PropertyGroup>
		<PublishReadyToRun Condition="'$(Configuration)' == 'Debug'">False</PublishReadyToRun>
		<PublishReadyToRun Condition="'$(Configuration)' != 'Debug'">True</PublishReadyToRun>
		<PublishTrimmed Condition="'$(Configuration)' == 'Debug'">False</PublishTrimmed>
		<PublishTrimmed Condition="'$(Configuration)' != 'Debug'">True</PublishTrimmed>
		<PlatformTarget>x64</PlatformTarget>
	</PropertyGroup>

	<Target Name="CopyControllerInput" AfterTargets="Build">
		<Copy SourceFiles="$(SolutionDir)x64\$(Configuration)\ControllerInput.dll" DestinationFolder="$(OutDir)" SkipUnchangedFiles="true" />
	</Target>

	<ItemGroup>
		<Content Include="$(SolutionDir)x64\$(Configuration)\ControllerInput.dll">
			<Link>ControllerInput.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Controls\ControllerGlyph.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Controls\ControllerPrompt.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Assets\ControllerGlyphs\Playstation\" />
	  <Folder Include="Assets\ControllerGlyphs\Xbox\" />
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Overlays\SteamQrLoginOverlay.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Controls\SteamChatMessageBubble.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Overlays\FriendChatPane.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Overlays\FriendsOverlay.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Views\FriendsView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Controls\SteamFriendCard.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Views\GameActivityView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Controls\ActivityFeedCard.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Controls\PlayedFriendAvatar.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Controls\FriendActivityCard.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Views\GamePageView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Overlays\GameContextMenu.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Overlays\GuideMenu.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Views\SettingsView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Views\HomeView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Controls\ControllerPromptBar.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
</Project>